version: '3'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: personal_hub
    volumes:
      - personal_hub_pg_data:/bitnami/postgresql
      - /etc/localtime:/etc/localtime:ro

volumes:
  personal_hub_pg_data: